name: MTL_CGC
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.*          
  - mkl=2024.*       
  - mkl-service=2.4.*
  - xarray=2023.12.*
  - geopandas=0.14.*
  - cartopy=0.22.*
  - seaborn=0.13.*
  - scikit-learn=1.4.*  
  - tqdm=4.66.*
  - hydroerr
  - pytorch=1.12.1
  - pytorch-scatter
  - tensorboard=2.15.*   
  - torchvision=0.13.1
  - pytest=8.0.*
  - black=24.*
  - flake8=7.*
  - ipykernel=6.28.*
  - jupyter=1.1.*
  - pip
  - pip:
    - tbparse>=0.0.9    